apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../gitops/base/infra

patches:
  - path: patches/kube-prometheus-stack-patch.yaml
  - path: patches/grafana-ingress-patch.yaml
